# Generated by Django 3.1 on 2021-06-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_facebook_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='facebook_id',
        ),
    ]
