# Generated by Django 3.2.4 on 2021-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='media/profile/default-FFA-avatar.png', null=True, upload_to='profile/'),
        ),
    ]
