# Generated by Django 3.2.4 on 2021-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_myuser_payment_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='payment_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
