# Generated by Django 2.2 on 2021-05-27 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('title', models.CharField(max_length=200, verbose_name='Isim')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ug', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_tk', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_tt', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ksk', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ba', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_cv', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ash', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_kaa', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_krc', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_sah', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ctt', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_alt', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('slug_tr', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_az', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_uz', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_kk', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_ug', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_tk', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_tt', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_ky', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_ksk', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_ba', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_cv', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_ash', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_kaa', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_krc', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_sah', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_ctt', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_alt', models.SlugField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Isim')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ug', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_tk', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_tt', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ksk', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ba', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_cv', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ash', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_kaa', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_krc', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_sah', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_ctt', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('title_alt', models.CharField(max_length=200, null=True, verbose_name='Isim')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favoriler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='description')),
                ('description', models.TextField(verbose_name='Metin')),
                ('description_tr', models.TextField(null=True, verbose_name='Metin')),
                ('description_az', models.TextField(null=True, verbose_name='Metin')),
                ('description_uz', models.TextField(null=True, verbose_name='Metin')),
                ('description_kk', models.TextField(null=True, verbose_name='Metin')),
                ('description_ug', models.TextField(null=True, verbose_name='Metin')),
                ('description_tk', models.TextField(null=True, verbose_name='Metin')),
                ('description_tt', models.TextField(null=True, verbose_name='Metin')),
                ('description_ky', models.TextField(null=True, verbose_name='Metin')),
                ('description_ksk', models.TextField(null=True, verbose_name='Metin')),
                ('description_ba', models.TextField(null=True, verbose_name='Metin')),
                ('description_cv', models.TextField(null=True, verbose_name='Metin')),
                ('description_ash', models.TextField(null=True, verbose_name='Metin')),
                ('description_kaa', models.TextField(null=True, verbose_name='Metin')),
                ('description_krc', models.TextField(null=True, verbose_name='Metin')),
                ('description_sah', models.TextField(null=True, verbose_name='Metin')),
                ('description_ctt', models.TextField(null=True, verbose_name='Metin')),
                ('description_alt', models.TextField(null=True, verbose_name='Metin')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Word')),
            ],
        ),
    ]
