# Generated by Django 3.1 on 2021-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Açıklama-Kelimesi'},
        ),
        migrations.RemoveField(
            model_name='description',
            name='description',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_alt',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_ash',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_ba',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_ctt',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_cv',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_kaa',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_krc',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_ksk',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_sah',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_tk',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_tt',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_ug',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_uz',
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Isim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='title_alt',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ash',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ba',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ctt',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_cv',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_kaa',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_krc',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ksk',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_sah',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_tk',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_tt',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ug',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
    ]
