# Generated by Django 3.1 on 2021-06-07 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Description',
            new_name='WordDescription',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='word',
        ),
        migrations.AddField(
            model_name='favorite',
            name='word_description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.worddescription'),
            preserve_default=False,
        ),
    ]
