# Generated by Django 3.1 on 2021-06-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210607_0546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordDescription',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='word_description',
        ),
        migrations.AddField(
            model_name='favorite',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.word'),
            preserve_default=False,
        ),
    ]
