# Generated by Django 3.1 on 2021-05-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210528_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favoriler'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Kelimeler'},
        ),
    ]
