# Generated by Django 3.2.4 on 2021-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210607_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name_plural': 'Описание-слов'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name_plural': 'Слово'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='description',
            name='audio_file_ru',
            field=models.FileField(null=True, upload_to='mp3'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Isim'),
        ),
        migrations.AddField(
            model_name='word',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Isim'),
        ),
    ]
