# Generated by Django 3.2.4 on 2021-06-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210611_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank='', max_length=200, null='', verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_alt',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ash',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_az',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ba',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ctt',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_cv',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_kaa',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_kk',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_krc',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ksk',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ky',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_sah',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_tk',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_tr',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_tt',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ug',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_uz',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_alt',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ash',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ba',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ctt',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_cv',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_kaa',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_krc',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ksk',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_sah',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_tk',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_tt',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ug',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Избранный'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория'),
        ),
    ]
