# Generated by Django 3.2.4 on 2021-06-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210611_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
