# Generated by Django 3.2.4 on 2021-06-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_description_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_alt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ash',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ba',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ctt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_cv',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_kaa',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_kk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_krc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ksk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_sah',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_tk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_tr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_tt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_uz',
        ),
    ]
