# Generated by Django 3.2.4 on 2021-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210611_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_ash',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_ba',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_ctt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_cv',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_kaa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_krc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_ksk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_sah',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_tk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_tt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_ug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
    ]
