# Generated by Django 3.2.4 on 2021-06-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210611_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_ctt',
            new_name='title_crh',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='audio_file_ctt',
            new_name='audio_file_crh',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='title_ctt',
            new_name='title_crh',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='title_ctt',
            new_name='title_crh',
        ),
    ]
