# Generated by Django 3.2.4 on 2021-06-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210614_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_alt',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_ash',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_az',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_ba',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_crh',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_cv',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_kaa',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_kk',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_krc',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_ksk',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_ky',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_ru',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_sah',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_tk',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_tr',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_tt',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_ug',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
        migrations.AddField(
            model_name='description',
            name='images_uz',
            field=models.ImageField(blank=True, null=True, upload_to='descriptions_country'),
        ),
    ]
