# Generated by Django 3.2.4 on 2021-06-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210616_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='description',
            name='audio_file_ru',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_alt',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_ash',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_az',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_ba',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_crh',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_cv',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_kaa',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_kk',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_krc',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_ksk',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_ky',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_ru',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_sah',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_tk',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_tr',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_tt',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_ug',
        ),
        migrations.RemoveField(
            model_name='description',
            name='images_uz',
        ),
        migrations.RemoveField(
            model_name='description',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='word',
            name='title_ru',
        ),
    ]
