# Generated by Django 3.2.4 on 2021-06-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210618_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='word',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='word',
        ),
        migrations.AddField(
            model_name='favorite',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.description'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
