# Generated by Django 3.2.4 on 2021-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210619_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AddField(
            model_name='description',
            name='audio_file_ru',
            field=models.FileField(null=True, upload_to='mp3'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Слово'),
        ),
    ]
