# Generated by Django 3.2.4 on 2021-06-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_description_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='description',
            name='audio_file_ru',
        ),
        migrations.RemoveField(
            model_name='description',
            name='title_ru',
        ),
    ]
