# Generated by Django 3.2.4 on 2021-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210619_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
