# Generated by Django 3.2.4 on 2021-06-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_favorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_alt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ba',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_crh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_cv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_kaa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_krc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ksk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_sah',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_tk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_tt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_ug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
