# Generated by Django 3.2.4 on 2021-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_category_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_alt',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_ash',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_az',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_ba',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_crh',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_cv',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_kaa',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_kk',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_krc',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_ksk',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_ky',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_sah',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_tk',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_tr',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_tt',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_ug',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='description',
            name='audio_file_uz',
            field=models.FileField(blank=True, null=True, upload_to='mp3'),
        ),
    ]
